/**
 * Helpdesk / ticketing schema — T-0184.
 *
 * `helpdesk_tickets` — header (subject, body, status, priority, category,
 * reporter/assignee, source). Tickets can be filed manually by a user
 * or auto-created by the AI assistant when a user reports an error.
 *
 * `helpdesk_ticket_replies` — append-only thread under a ticket. Internal
 * notes (`isInternal=true`) are visible only to handlers; otherwise the
 * reporter sees them too.
 */

import { boolean, index, integer, jsonb, pgTable, text, timestamp } from 'drizzle-orm/pg-core';
import { auditCols, pk, tenantCol } from './common';

export const helpdeskTickets = pgTable(
  'helpdesk_tickets',
  {
    ...pk,
    ...tenantCol,

    // Human-readable number — TKT-YYYY-MM-####, generated by service.
    number: text('number').notNull(),

    subject: text('subject').notNull(),
    body: text('body').notNull(),

    // open | in_progress | waiting_reporter | resolved | closed
    status: text('status').notNull().default('open'),
    // low | normal | high | urgent
    priority: text('priority').notNull().default('normal'),
    // bug | request | question | other
    category: text('category').notNull().default('other'),

    reporterUserId: text('reporter_user_id').notNull(),
    assigneeUserId: text('assignee_user_id'),

    // 'manual' | 'ai_chat' — so we can see how many tickets the AI filed.
    createdVia: text('created_via').notNull().default('manual'),

    // When created_via='ai_chat', track the source session so the
    // handler can read the conversation for context.
    sourceAiSessionId: text('source_ai_session_id'),

    // Free-form structured context (browser info, current URL,
    // affected entity refs). The AI fills this when relevant.
    contextJson: jsonb('context_json'),

    closedAt: timestamp('closed_at', { withTimezone: true }),
    resolvedAt: timestamp('resolved_at', { withTimezone: true }),
    firstResponseAt: timestamp('first_response_at', { withTimezone: true }),

    // T-0262: SLA and escalation
    slaDueDate: timestamp('sla_due_date', { withTimezone: true }),
    isSlaBreached: boolean('is_sla_breached').notNull().default(false),
    escalationLevel: integer('escalation_level').notNull().default(0),

    ...auditCols,
  },
  (t) => [
    index('helpdesk_tickets_tenant_idx').on(t.tenantId),
    index('helpdesk_tickets_status_idx').on(t.status),
    index('helpdesk_tickets_reporter_idx').on(t.reporterUserId),
    index('helpdesk_tickets_assignee_idx').on(t.assigneeUserId),
    index('helpdesk_tickets_number_idx').on(t.number),
    index('helpdesk_tickets_created_via_idx').on(t.createdVia),
  ],
);

export const helpdeskTicketReplies = pgTable(
  'helpdesk_ticket_replies',
  {
    ...pk,

    ticketId: text('ticket_id').notNull(),

    authorUserId: text('author_user_id').notNull(),

    body: text('body').notNull(),

    // Internal notes are visible to handlers only.
    isInternal: boolean('is_internal').notNull().default(false),

    ...auditCols,
  },
  (t) => [
    index('helpdesk_ticket_replies_ticket_idx').on(t.ticketId),
    index('helpdesk_ticket_replies_author_idx').on(t.authorUserId),
  ],
);
