/**
 * MCP Tool registry — re-exports all tool arrays and definitions.
 */

export {
  iamTools,
  ListLocationsSchema,
  UpsertLocationSchema,
  DeleteLocationSchema,
  WhoamiSchema,
} from './iam';

export {
  accountingTools,
  ListAccountsSchema,
  CreateJournalSchema,
  PostJournalSchema,
  ReverseJournalSchema,
  GetPeriodStatusSchema,
  ClosePeriodSchema,
  ListFixedAssetCategoriesSchema,
  ListFixedAssetsMcpSchema,
  CreateFixedAssetMcpSchema,
  RunFixedAssetDepreciationMcpSchema,
  GetJournalWithAttachmentsSchema,
  ListJournalAttachmentsSchema,
  UpsertAccountSchema,
  DeleteAccountSchema,
} from './accounting';

export {
  taxTools,
  ListRatesSchema,
  ExportCoretaxSchema,
  UpsertTaxRateSchema,
  DeleteTaxRateSchema,
  ListTaxRulesSchema,
  UpsertTaxRuleSchema,
  DeleteTaxRuleSchema,
} from './tax';

export {
  reportingTools,
  BalanceSheetSchema,
  ProfitLossSchema,
  CashFlowSchema,
  GeneralLedgerSchema,
  TrialBalanceSchema,
  DailySummarySchema,
} from './reporting';

export {
  inventoryTools,
  InventoryListCategoriesSchema,
  InventoryUpsertCategorySchema,
  InventoryDeleteCategorySchema,
  InventoryListProductsSchema,
  InventoryGetStockSchema,
  InventoryAdjustSchema,
  purchasingTools,
  PurchasingCreatePOSchema,
  PurchasingApprovePOSchema,
  PurchasingCreateGRNSchema,
  posTools,
  POSListSalesSchema,
  POSRefundSchema,
  hrTools,
  HRCreateEmployeeSchema,
  HRListEmployeesSchema,
  payrollTools,
  PayrollRunSchema,
  PayrollApproveSchema,
  PayrollMarkPaidSchema,
  disciplinaryTools,
  DisciplinaryCreateSchema,
  DisciplinaryAcknowledgeSchema,
  DisciplinaryListSchema,
  crmTools,
  CRMCreateMemberSchema,
  CRMLogComplaintSchema,
  CRMListComplaintsSchema,
  CRMResolveComplaintSchema,
  memberTools,
  MemberGetLoyaltySchema,
  MemberGetVouchersSchema,
  MemberRedeemPointsSchema,
  promotionTools,
  PromotionListSchema,
  PromotionUpsertSchema,
  docsTools,
  DocsGetSchema,
  DocsUpdateSchema,
  operationsTools,
  ScheduledJobListSchema,
  ScheduledJobUpdateSchema,
  NotificationChannelListSchema,
  NotificationChannelUpsertSchema,
  auditTools,
  AuditSearchSchema,
} from './phase2';
