/**
 * COA Seed - SOURCE-OF-TRUTH Lampiran A.
 *
 * Codes follow the user-provided legacy Aroadri Tea COA. Additional system accounts
 * are kept minimal and clearly separated.
 */

import type { LocaleString } from '@erp/shared/types';

type AccountSeed = {
  code: string;
  name: LocaleString;
  type: 'asset' | 'liability' | 'equity' | 'income' | 'cogs' | 'expense';
  subtype: string;
  normalBalance: 'debit' | 'credit';
  isPostable: boolean;
};

const n = (id: string, en: string, zh: string): LocaleString => ({ id, en, zh });

const account = (
  code: string,
  id: string,
  en: string,
  zh: string,
  type: AccountSeed['type'],
  subtype: string,
  normalBalance: AccountSeed['normalBalance'],
  isPostable = true,
): AccountSeed => ({
  code,
  name: n(id, en, zh),
  type,
  subtype,
  normalBalance,
  isPostable,
});

export const COA_SEED: AccountSeed[] = [
  account('1-0000', 'Aktiva', 'Assets', '资产', 'asset', 'header', 'debit', false),
  account('1-1100', 'Kas Kecil', 'Petty Cash', '零用金', 'asset', 'current_asset', 'debit'),
  account('1-1200', 'Kas', 'Cash', '现金', 'asset', 'current_asset', 'debit'),
  account('1-1300', 'Kas di Bank', 'Cash in Bank', '银行存款', 'asset', 'current_asset', 'debit'),
  account(
    '1-1400',
    'Pingpong Payment',
    'Pingpong Payment',
    'Pingpong Payment',
    'asset',
    'current_asset',
    'debit',
  ),
  account(
    '1-1500',
    'Piutang Usaha',
    'Account Receivable',
    '应收账款',
    'asset',
    'current_asset',
    'debit',
  ),
  account(
    '1-1510',
    'Cadangan Kerugian Piutang',
    'Allowance for Doubtful Debt',
    '坏账准备',
    'asset',
    'contra_asset',
    'credit',
  ),
  account(
    '1-1600',
    'Persediaan Barang Dagangan',
    'Merchandise Inventory',
    '商品库存',
    'asset',
    'current_asset',
    'debit',
  ),
  account(
    '1-1700',
    'Perlengkapan Kantor',
    'Office Supplies',
    '办公用品',
    'asset',
    'current_asset',
    'debit',
  ),
  account(
    '1-1800',
    'Perlengkapan Toko',
    'Store Supplies',
    '店铺用品',
    'asset',
    'current_asset',
    'debit',
  ),
  account(
    '1-1900',
    'Beban Dibayar Dimuka',
    'Prepaid Expense',
    '预付费用',
    'asset',
    'current_asset',
    'debit',
  ),
  account(
    '1-2000',
    'Sewa Dibayar Dimuka - Kantor Jakarta',
    'Prepaid Rent of Jakarta Office',
    '预付租金-雅加达办公室',
    'asset',
    'current_asset',
    'debit',
  ),
  account(
    '1-2100',
    'Sewa Dibayar Dimuka - Kantor Yogyakarta',
    'Prepaid Rent of Yogyakarta Office',
    '预付租金-日惹办公室',
    'asset',
    'current_asset',
    'debit',
  ),
  account(
    '1-2200',
    'Sewa Dibayar Dimuka - Toko Malioboro',
    'Prepaid Rent of Malioboro Store',
    '预付租金-马里奥波罗门店',
    'asset',
    'current_asset',
    'debit',
  ),
  account(
    '1-2300',
    'Deposit Jaminan Kantor Jakarta',
    'Jakarta Office Security Deposit',
    '保证金-雅加达办公室',
    'asset',
    'current_asset',
    'debit',
  ),
  account(
    '1-2400',
    'Deposit Jaminan Kantor Yogyakarta',
    'Yogyakarta Office Security Deposit',
    '保证金-日惹办公室',
    'asset',
    'current_asset',
    'debit',
  ),
  account(
    '1-2500',
    'Deposit Jaminan Toko',
    'Store Security Deposit',
    '保证金-门店',
    'asset',
    'current_asset',
    'debit',
  ),
  account(
    '1-2600',
    'PPh Final Dibayar Dimuka',
    'Prepaid Final Tax',
    '预缴最终所得税',
    'asset',
    'current_asset',
    'debit',
  ),
  account(
    '1-2700',
    'PBJT Dibayar Dimuka',
    'Prepaid PBJT Tax',
    '预缴餐饮税',
    'asset',
    'current_asset',
    'debit',
  ),
  account(
    '1-2800',
    'Sewa Dibayar Dimuka',
    'Prepaid Rent',
    '预付租金',
    'asset',
    'current_asset',
    'debit',
  ),
  account('1-3100', 'Investasi', 'Investment', '投资', 'asset', 'fixed_asset', 'debit'),
  account(
    '1-4100',
    'PPN Masukan',
    'Vat In (PPN Income)',
    '进项增值税',
    'asset',
    'current_asset',
    'debit',
  ),
  account(
    '1-4200',
    'Konstruksi dalam Proses',
    'Construction in Progress',
    '在建工程',
    'asset',
    'fixed_asset',
    'debit',
  ),
  account(
    '1-4300',
    'Renovasi / Leasehold Improvement',
    'Renovasi / Leasehold Improvement',
    '租赁装修',
    'asset',
    'fixed_asset',
    'debit',
  ),
  account(
    '1-4400',
    'Peralatan Toko',
    'Store Equipment',
    '店铺设备',
    'asset',
    'fixed_asset',
    'debit',
  ),
  account(
    '1-4410',
    'Akumulasi Penyusutan Peralatan Toko',
    'Accumulated Depreciation Of Store Equipment',
    '累计折旧-店铺设备',
    'asset',
    'contra_asset',
    'credit',
  ),
  account(
    '1-4500',
    'Peralatan Kantor',
    'Office Equipment',
    '办公设备',
    'asset',
    'fixed_asset',
    'debit',
  ),
  account(
    '1-4510',
    'Akumulasi Penyusutan Peralatan Kantor',
    'Accumulated Depreciation Of Office Equipment',
    '累计折旧-办公设备',
    'asset',
    'contra_asset',
    'credit',
  ),
  account('1-4600', 'Mesin', 'Machine', '机器', 'asset', 'fixed_asset', 'debit'),
  account(
    '1-4610',
    'Akumulasi Penyusutan Mesin',
    'Accumulated Depreciation Of Machine',
    '累计折旧-机器',
    'asset',
    'contra_asset',
    'credit',
  ),
  account('1-4700', 'Merek Dagang', 'Trademarks', '商标', 'asset', 'fixed_asset', 'debit'),
  account(
    '1-4710',
    'Akumulasi Penyusutan Merek Dagang',
    'Accumulated Depreciation Of Trademark',
    '累计折旧-商标',
    'asset',
    'contra_asset',
    'credit',
  ),
  account(
    '1-4800',
    'Furnitur dan Perlengkapan',
    'Furnitur and fixture',
    '家具及装置',
    'asset',
    'fixed_asset',
    'debit',
  ),
  account(
    '1-4810',
    'Akumulasi Penyusutan Furnitur dan Perlengkapan',
    'Accumulated Depreciation Of Furnitur and fixture',
    '累计折旧-家具及装置',
    'asset',
    'contra_asset',
    'credit',
  ),

  account('2-0000', 'Kewajiban', 'Liabilities', '负债', 'liability', 'header', 'credit', false),
  account(
    '2-1100',
    'Utang Usaha',
    'Account Payable',
    '应付账款',
    'liability',
    'current_liability',
    'credit',
  ),
  account(
    '2-1110',
    'Penerimaan Belum Ditagih (GRNI)',
    'Goods Received Not Invoiced',
    '未开票收货',
    'liability',
    'current_liability',
    'credit',
  ),
  account(
    '2-1200',
    'Utang Beban',
    'Expense Payable',
    '应付费用',
    'liability',
    'current_liability',
    'credit',
  ),
  account(
    '2-1300',
    'Utang Pajak Penghasilan',
    'Income Tax Payable',
    '应付所得税',
    'liability',
    'current_liability',
    'credit',
  ),
  account(
    '2-1400',
    'Utang PPN',
    'PPN Payable',
    '应付增值税',
    'liability',
    'current_liability',
    'credit',
  ),
  account(
    '2-1500',
    'Utang PB1 / PBJT',
    'PB1 / PBJT Payable',
    '应付餐饮税',
    'liability',
    'current_liability',
    'credit',
  ),
  account(
    '2-1600',
    'Utang Gaji',
    'Salaries Payable',
    '应付工资',
    'liability',
    'current_liability',
    'credit',
  ),
  account(
    '2-1700',
    'Utang PPh Final',
    'Final Income Tax Payable',
    '应付最终所得税',
    'liability',
    'current_liability',
    'credit',
  ),
  account(
    '2-1800',
    'Utang PPh Final 23',
    'Final Income Tax 23 Payable',
    '应付第23条所得税',
    'liability',
    'current_liability',
    'credit',
  ),
  account(
    '2-1900',
    'Utang kepada Pemilik',
    'Due to Owner',
    '应付业主',
    'liability',
    'current_liability',
    'credit',
  ),
  account(
    '2-2000',
    'Utang Reimbursement',
    'Reimbursement Payable',
    '应付报销',
    'liability',
    'current_liability',
    'credit',
  ),
  account(
    '2-2050',
    'Utang Titipan Donasi',
    'Donation Trust Payable',
    '应付慈善代收款',
    'liability',
    'current_liability',
    'credit',
  ),
  account(
    '2-2100',
    'Kewajiban Jangka Panjang',
    'Long Term Liabilites',
    '长期负债',
    'liability',
    'long_term_liability',
    'credit',
  ),
  account(
    '2-2200',
    'Pinjaman Bank BCA',
    'Bank BCA Loan',
    'BCA银行贷款',
    'liability',
    'long_term_liability',
    'credit',
  ),
  account(
    '2-2300',
    'PPN Keluaran',
    'PPN Outcome (Vat Out)',
    '销项增值税',
    'liability',
    'current_liability',
    'credit',
  ),

  account('3-0000', 'Ekuitas', 'Equity', '权益', 'equity', 'header', 'credit', false),
  account('3-1100', 'Modal Saham', 'Common Stock', '股本', 'equity', 'equity', 'credit'),
  account('3-1200', 'Dividen', 'Devidend', '股利', 'equity', 'equity', 'debit'),
  account(
    '3-1300',
    'Ikhtisar Laba Rugi',
    'Income Summary',
    '损益汇总',
    'equity',
    'equity',
    'credit',
  ),
  account('3-1400', 'Laba Ditahan', 'Retained Earning', '留存收益', 'equity', 'equity', 'credit'),

  account('4-0000', 'Pendapatan', 'Revenue', '收入', 'income', 'header', 'credit', false),
  account('4-1100', 'Penjualan', 'Sales', '销售收入', 'income', 'revenue', 'credit'),
  account(
    '4-1200',
    'Retur Penjualan',
    'Sales Return',
    '销售退回',
    'income',
    'contra_revenue',
    'debit',
  ),
  account(
    '4-1400',
    'Diskon Penjualan',
    'Sales Discount',
    '销售折扣',
    'income',
    'contra_revenue',
    'debit',
  ),

  account(
    '5-0000',
    'Harga Pokok Penjualan',
    'Cost of Goods Sold',
    '销售成本',
    'cogs',
    'header',
    'debit',
    false,
  ),
  account('5-1100', 'Pembelian', 'Purchase', '采购', 'cogs', 'cogs', 'debit'),
  account(
    '5-1200',
    'Retur Pembelian',
    'Purchase Return',
    '采购退回',
    'cogs',
    'contra_cogs',
    'credit',
  ),
  account(
    '5-1300',
    'Diskon Pembelian',
    'Purchase Discount',
    '采购折扣',
    'cogs',
    'contra_cogs',
    'credit',
  ),
  account('5-1400', 'Persediaan Awal', 'Beginning Inventory', '期初库存', 'cogs', 'cogs', 'debit'),
  account('5-1410', 'Persediaan Akhir', 'Ending Inventory', '期末库存', 'cogs', 'cogs', 'credit'),
  account(
    '5-1500',
    'Ongkos Angkut Masuk',
    'Freight Paid / Freight In',
    '进货运费',
    'cogs',
    'cogs',
    'debit',
  ),

  account(
    '6-0000',
    'Beban Operasional',
    'Operating Expenses',
    '营业费用',
    'expense',
    'header',
    'debit',
    false,
  ),
  account(
    '6-1100',
    'Beban Iklan',
    'Advertising Expense',
    '广告费',
    'expense',
    'operating',
    'debit',
  ),
  account(
    '6-1200',
    'Beban Utilitas Kantor Jakarta',
    'Jakarta Office Utilities Expense',
    '雅加达办公室水电费',
    'expense',
    'operating',
    'debit',
  ),
  account(
    '6-1300',
    'Beban Utilitas Kantor Yogyakarta',
    'Yogyakarta Office Utilities  Expense',
    '日惹办公室水电费',
    'expense',
    'operating',
    'debit',
  ),
  account(
    '6-1400',
    'Beban Utilitas Toko',
    'Store Utilities Expense',
    '店铺水电费',
    'expense',
    'operating',
    'debit',
  ),
  account(
    '6-1500',
    'Beban Piutang Tak Tertagih',
    'Bad Debt Expense',
    '坏账费用',
    'expense',
    'operating',
    'debit',
  ),
  account(
    '6-1600',
    'Beban Penyusutan',
    'Depreciation Expense',
    '折旧费用',
    'expense',
    'depreciation',
    'debit',
  ),
  account(
    '6-1700',
    'Beban Instalasi',
    'Installation Expense',
    '安装费',
    'expense',
    'operating',
    'debit',
  ),
  account(
    '6-1800',
    'Beban Sewa Toko',
    'Store Rent Expense',
    '店铺租金',
    'expense',
    'operating',
    'debit',
  ),
  account(
    '6-1900',
    'Beban Sewa Kantor',
    'Office Rent Expense',
    '办公室租金',
    'expense',
    'operating',
    'debit',
  ),
  account(
    '6-2000',
    'Beban Gaji dan Upah',
    'Wages and Salaries Expense',
    '工资薪金费用',
    'expense',
    'operating',
    'debit',
  ),
  account(
    '6-2100',
    'Beban Operasional Lainnya',
    'Others Operating Expense',
    '其他营业费用',
    'expense',
    'operating',
    'debit',
  ),
  account(
    '6-2200',
    'Beban Gaji Kantor',
    'Office Salaries Expense',
    '办公室薪资',
    'expense',
    'operating',
    'debit',
  ),
  account(
    '6-2300',
    'Beban Gaji Toko',
    'Store Salaries Expense',
    '店铺薪资',
    'expense',
    'operating',
    'debit',
  ),
  account(
    '6-2400',
    'Beban Perlengkapan Kantor',
    'Office Supplies Expense',
    '办公用品费用',
    'expense',
    'operating',
    'debit',
  ),
  account(
    '6-2500',
    'Beban Perlengkapan Toko',
    'Store Supplies Expense',
    '店铺用品费用',
    'expense',
    'operating',
    'debit',
  ),
  account(
    '6-2600',
    'Beban Administrasi',
    'Administrative Expense',
    '行政费用',
    'expense',
    'operating',
    'debit',
  ),
  account(
    '6-2700',
    'Beban Pemeliharaan Properti',
    'Property Maintenance Expense',
    '物业维护费',
    'expense',
    'operating',
    'debit',
  ),
  account(
    '6-2800',
    'Beban Pra-Operasi',
    'Pre-Operation Expenses',
    '开办费',
    'expense',
    'operating',
    'debit',
  ),
  account('6-2900', 'Beban Sewa', 'Rent Expense', '租金费用', 'expense', 'operating', 'debit'),
  account(
    '6-3000',
    'Beban Penyusutan Furnitur dan Perlengkapan',
    'Depreciation Expense of Furniture and Fixture',
    '家具及装置折旧费',
    'expense',
    'depreciation',
    'debit',
  ),
  account(
    '6-3100',
    'Beban Penyusutan Mesin',
    'Depreciation Expense of Machine',
    '机器折旧费',
    'expense',
    'depreciation',
    'debit',
  ),
  account(
    '6-3200',
    'Beban Penyusutan Peralatan Kantor',
    'Depreciation Expense of office Equipment',
    '办公设备折旧费',
    'expense',
    'depreciation',
    'debit',
  ),
  account(
    '6-3300',
    'Beban Penyusutan Peralatan Toko',
    'Depreciation Expense of Store Equipment',
    '店铺设备折旧费',
    'expense',
    'depreciation',
    'debit',
  ),
  account(
    '6-3400',
    'Beban Penyusutan Merek Dagang',
    'Depreciation Expense of Trademark',
    '商标折旧费',
    'expense',
    'depreciation',
    'debit',
  ),
  account(
    '6-3500',
    'Beban PPh Final Sewa',
    'Final Rental Tax Expense',
    '租赁最终税费用',
    'expense',
    'operating',
    'debit',
  ),
  account(
    '6-3600',
    'Beban Komisi',
    'Commission Expense',
    '佣金费用',
    'expense',
    'operating',
    'debit',
  ),
  account(
    '6-3700',
    'Ongkos Angkut Keluar',
    'Freight Out',
    '出货运费',
    'expense',
    'operating',
    'debit',
  ),
  account(
    '6-3800',
    'Beban Sewa Kantor Jakarta',
    'Jakarta Office Rent Expense',
    '雅加达办公室租金',
    'expense',
    'operating',
    'debit',
  ),
  account(
    '6-3900',
    'Beban Sewa Kantor Yogyakarta',
    'Yogyakarta Office Rent Expense',
    '日惹办公室租金',
    'expense',
    'operating',
    'debit',
  ),
  account('6-4000', 'Beban PJU', 'PJU Expense', '公共照明税费', 'expense', 'operating', 'debit'),
  account(
    '6-4100',
    'Beban Transportasi',
    'Transportation Expense',
    '交通费',
    'expense',
    'operating',
    'debit',
  ),
  account(
    '6-4200',
    'Beban Komunikasi',
    'Comunication Expense',
    '通讯费',
    'expense',
    'operating',
    'debit',
  ),

  account(
    '7-0000',
    'Pendapatan dan Beban Lainnya',
    'Other Income and Expense',
    '其他收支',
    'expense',
    'header',
    'debit',
    false,
  ),
  account(
    '7-1100',
    'Pendapatan Bunga',
    'Interest Revenue',
    '利息收入',
    'income',
    'other_income',
    'credit',
  ),
  account(
    '7-1200',
    'Pendapatan Lainnya',
    'Other Income',
    '其他收入',
    'income',
    'other_income',
    'credit',
  ),
  account(
    '7-2100',
    'Beban Bunga',
    'Interest Expense',
    '利息费用',
    'expense',
    'non_operating',
    'debit',
  ),
  account(
    '7-3100',
    'Beban Administrasi Bank',
    'Bank Administration Fees',
    '银行手续费',
    'expense',
    'non_operating',
    'debit',
  ),
  account(
    '7-4100',
    'Beban Pajak Penghasilan',
    'Income Tax Expenses',
    '所得税费用',
    'expense',
    'income_tax',
    'debit',
  ),
];

const ACTIVE_COA_CODES = new Set(COA_SEED.map((acct) => acct.code));

export const LEGACY_COA_CODES_TO_DEACTIVATE = [
  '1-1010',
  '1-1020',
  '1-1030',
  '1-1040',
  '1-1110',
  '1-1120',
  '1-1210',
  '1-1310',
  '1-1320',
  '1-1410',
  '1-1420',
  '1-1430',
  '1-1440',
  '1-1510',
  '1-1520',
  '1-1530',
  '1-1610',
  '1-1620',
  '1-1630',
  '1-1640',
  '1-2010',
  '1-2020',
  '1-2030',
  '1-2110',
  '1-2111',
  '1-2120',
  '1-2121',
  '1-2130',
  '1-2131',
  '1-2140',
  '1-2141',
  '1-2150',
  '1-2151',
  '2-1010',
  '2-1020',
  '2-1030',
  '2-1040',
  '2-1050',
  '2-1060',
  '2-1070',
  '2-1080',
  '2-1090',
  '2-1100',
  '2-1110',
  '2-1120',
  '2-2010',
  '2-2020',
  '3-1010',
  '3-1020',
  '3-1030',
  '3-1040',
  '4-1010',
  '4-1020',
  '4-1030',
  '4-2010',
  '4-2020',
  '5-1010',
  '5-1020',
  '5-1030',
  '5-1040',
  '5-1050',
  '5-1060',
  '6-1010',
  '6-1020',
  '6-1030',
  '6-1040',
  '6-1050',
  '6-1060',
  '6-1070',
  '6-1080',
  '6-1090',
  '6-1100',
  '6-1110',
  '6-1120',
  '6-1130',
  '6-1140',
  '6-1150',
  '6-1160',
  '6-1170',
  '6-1180',
  '6-1190',
  '6-1200',
  '6-1210',
  '6-1220',
  '6-1230',
  '6-1240',
  '6-1250',
  '6-1260',
  '6-1270',
  '6-1280',
  '6-1290',
  '6-1300',
  '6-1310',
  '6-1320',
  '7-1010',
  '7-1020',
  '7-1030',
].filter((code) => !ACTIVE_COA_CODES.has(code));
